# Generated by Django 4.1.5 on 2023-02-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=127, null=True, verbose_name='название')),
                ('parent', models.CharField(max_length=127, verbose_name='родитель')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Вотсап')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Твиттер')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Фейсбук')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('admissiontouniversity', models.CharField(blank=True, max_length=120, null=True, verbose_name='Поступлений в Университет')),
                ('staff', models.CharField(blank=True, max_length=120, null=True, verbose_name='Сотрудников')),
                ('students', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количествое учеников')),
                ('successworkyear', models.CharField(blank=True, max_length=120, null=True, verbose_name='Успешных лет')),
                ('mail', models.URLField(verbose_name='Почта')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('number', models.PositiveIntegerField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=120, verbose_name='Должность')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('photo', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='mainapp.school')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=127, verbose_name='автор')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создание')),
                ('description', models.TextField(verbose_name='описание')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='mainapp.school')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='image/')),
                ('name', models.CharField(max_length=127, null=True, verbose_name='название')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='mainapp.school')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
    ]
